### ISSUE TITLE
Bugstack errors for missing entries

### ISSUE THREAD

**Issue by HaraiUlfsark** [elling19/HappyButton#1]
Hello, this addon might just be what I'm looking for, however bugstack is displaying these errors when it is installed, and I cannot see any of the bars I try to create

I'm playing retail wow version 11.0.5.57388, English US language

> 2x AceLocale-3.0-6: HappyButton: Missing entry for 'Toy'
> [string "@HappyButton/Src/Const.lua"]:63: in main chunk
> 
> Locals:
> addonName = "HappyButton"
> _ = <table> {
>  modules = <table> {
>  }
>  defaultModuleLibraries = <table> {
>  }
>  name = "HappyButton"
>  orderedModules = <table> {
>  }
>  enabledState = true
>  defaultModuleState = false
>  hooks = <table> {
>  }
> }
> addon = <table> {
>  modules = <table> {
>  }
>  defaultModuleLibraries = <table> {
>  }
>  name = "HappyButton"
>  orderedModules = <table> {
>  }
>  enabledState = true
>  defaultModuleState = false
>  hooks = <table> {
>  }
> }
> L = <table> {
>  Btn Hide = "Btn Hide"
>  Use root element settings = "Use root element settings"
>  Mount = "Mount"
>  New ItemGroup = "New ItemGroup"
>  AttachFrame Anchor Position = "AttachFrame Anchor Position"
>  Items Source = "Items Source"
>  Debuff = "Debuff"
>  Mode = "Mode"
>  Add Text = "Add Text"
>  Add Child Elements = "Add Child Elements"
>  Window Position X = "Window Position X"
>  Type = "Type"
>  Select type = "Select type"
>  Monk = "Monk"
>  False = "False"
>  Open = "Open"
>  LEFT = "LEFT"
>  Warlock = "Warlock"
>  Aura Remaining Time = "Aura Remaining Time"
>  Whether to overwrite the existing configuration. = "Whether to overwrite the existing configuration."
>  Mail = "Mail"
>  Bindkey Settings = "Bindkey Settings"
>  Welcome to use HappyButton. = "Welcome to use HappyButton."
>  Unable to get the name, please check the input. = "Unable to get the name, please check the input."
>  Move Top Level = "Move Top Level"
>  Buff = "Buff"
>  Element Settings = "Element Settings"
>  Class = "Class"
>  LEFTBOTTOM = "LEFTBOTTOM"
>  Target = "Target"
>  New Condition = "New Condition"
>  CENTER = "CENTER"
>  WorldMapFrame = "WorldMapFrame"
>  TOPLEFT = "TOPLEFT"
>  Configuration String Edit Box = "Configuration String Edit Box"
>  Evoker = "Evoker"
>  Default = "Default"
>  Display = "Display"
>  Horizontal = "Horizontal"
>  General Settings = "General Settings"
>  Bar = "Bar"
>  Bind For Current Class = "Bind For Current Class"
>  Merchant = "Merchant"
>  Yes = "Yes"
>  Select Aura Type = "Select Aura Type"
>  Whether to show the bar menu when the mouse enter. = "Whether to show the bar menu when the mouse enter."
>  Vertical = "Vertical"
>  BOTTOMLEFT = "BOTTOMLEFT"
>  Element Icon ID or Path = "Element Icon ID or Path"
>  New Item = "New Item"
>  Delete = "Delete"
>  Script = "Script"
>  Main frame = "Main frame"
>  RIGHT = "RIGHT"
>  Edit Child Elements = "Edit Child Elements"
>  Please select item type. = "Please select item type."
>  Left-click to drag and move, right-click to exit edit mode. = "Left-click to drag and move, right-click to exit edit mode."
>  New Items Group = "New Items Group"
>  Display Rule = "Display Rule"
>  ITEM_GROUP = "ItemsGroup"
>  Display one item, selected sequentially. = "Display one item, selected sequentially."
>  isLearned = "Is Learned"
>  Items Bar = "Items Bar"
>  Cond1 and Cond2 and Cond3 = "Cond1 and Cond2 and Cond3"
>  TOPRIGHT = "TOPRIGHT"
>  Border Glow = "Border Glow"
>  Display as alone items bar = "Display as alone items bar"
>  Element Anchor Position = "Element Anchor Position"
>  Icon Height = "Icon Height"
>  New Trigger = "New Trigger"
>  Item name or item id = "Item name or item id"
>  Aura ID = "Aura ID"
>  Pet = "Pet"
>  (Cond1 and Cond2) or Cond3 = "(Cond1 and Cond2) or Cond3"
>  Condition Group = "Condition Group"
>  Enable Event Listening = "Enable Event Listening"
>  Element Title = "Element Title"
>  Load = "Load"
>  Cond1 and Cond2 = "Cond1 and Cond2"
>  Export = "Export"
>  Bind For Current Character = "Bind For Current Character"
>  GameMenuFrame = "GameMenuFrame"
>  Toy = "Toy"
>  Bind For Account = "Bind For Account"
>  Drawer Layout = "Drawer Layout"
>  Demon Hunter = "Demon Hunter"
>  BOTTOM = "BOTTOM"
>  Bindkey = "Bindkey"
>  Druid = "Druid"
>  Alias = "Alias"
>  Relative Y-Offset = "Relative Y-Offset"
>  Mage = "Mage"
>  Shaman = "Shaman"
>  You cannot use this in combat. = "You cannot use this in combat."
>  ItemGroup = "ItemGroup"
>  Death Knight = "Death Knight"
>  targetIsEnemy = "Target Is Enemy"
>  Load when out of combat = "Load when out of combat"
>  Priest = "Priest"
>  New Condition Group = "New Condition Group"
>  Load Rule = "Load Rule"
>  Btn Desaturate = "Btn Desaturate"
>  Window Position Y = "Window Position Y"
>  Hunter = "Hunter"
>  Icon = "Icon"
>  Whether to display item name. = "Whether to displa

**Comment by elling19** [comment]
Thank you for your bug report. This bug has been fixed. Please go to CurseForge to download the latest version.
